import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    nav: {
      home: 'Home',
      modules: 'Modules',
      about: 'About',
      contact: 'Contact',
      imprint: 'Imprint',
      guidedSimulator: 'Guided Simulator',
      promptPlayground: 'Prompt Playground'
    },
    landing: {
      hero: {
        title: 'PromptED: Responsible AI use in Journalism',
        subtitle: 'A hands-on exploration and practice for journalists to observe how large language models function, their limitations, and how to use them for more trustworthy content production.',
        watchTrailer: 'Watch Trailer'
      },
      features: {
        simulator: {
          title: 'Guided Simulator',
          description: 'Interactive guide: explore how LLMs work and how to responsibly interact with them'
        },
        playground: {
          title: 'Prompt Playground',
          description: 'Apply your knowledge: experiment with your own prompts'
        },
        debunker: {
          title: 'AI Claim Debunker',
          description: 'Put your skills to work: review claims and gain counter perspectives'
        }
      },
      footer: {
        llmUsage: 'LLMs have been used in the following ways:',
        guidedExploration: 'Guided Exploration:',
        guidedExplorationDesc: 'To create prompt-output examples.',
        promptPlayground: 'Prompt Playground:',
        promptPlaygroundDesc: 'To optimize prompts, generate outputs and to identify factual inaccuracies and bias.',
        modelsUsed: 'Models used:',
        models: 'Llama 3.1 8B, Mistral, Claude, ChatGPT',
        euFunding: "Funded by the European Union's Horizon Europe Programme (Grant 101135437)"
      }
    },
    modules: {
      title: 'Modules',
      comingSoon: 'Coming soon...',
      introduction: 'Introduction',
      nextWordPrediction: 'Next Word Prediction',
      promptConstruction: 'Prompt Construction'
    },
    intro: {
      aboutSimulator: {
        label: 'About this Simulator',
        title: 'What is a "Guided Simulator"?',
        description: 'A structured walkthrough of case studies generated by real-life LLM outputs that demonstrate key learnings. Interact at set points—sometimes more, sometimes less—always with clear guidance.',
        llmsUsed: 'LLMs used in the generation of text include: Mistral, Claude, Chat GPT & Llama 3.1 8B',
        continue: 'Continue'
      },
      base: {
        label: 'Introduction',
        title: 'Reporting on the EU AI Act',
        description: "In this simulator, you'll step into the role of a journalist preparing an article on the EU AI Act. Rather than starting from scratch, you'll work with preset prompts and see the real outputs generated by a large language model.",
        startSimulator: 'Start Simulator'
      }
    },
    nextWord: {
      intro: {
        label: 'Learning 1: Next word prediction',
        title: 'How do LLMs form responses to user prompts?',
        description: 'LLMs generate text by predicting what word should come next. For each prediction, previous words are analysed to calculate probabilities for all possible next words. The most probable word is selected, added to the text, and then used in this updated context to predict the next word, continuing until complete.',
        continue: 'Continue'
      }
    },
    promptConstructionModule: {
      intro: {
        label: 'Learning 2: Prompt construction',
        title: "How does my input affect the quality of the LLM's output?",
        description: "Your prompt directly shapes an LLM's response. Large language models use the wording, specificity, and context in your wording to help decide how to reply, meaning the quality of the output can depend heavily on how you phrase it. Explore how real LLM generated responses change with different prompt constructions",
        continue: 'Continue'
      }
    },
    about: {
      title: 'About',
      description: 'This is the About page. Information about the project will be added here soon.'
    },
    contact: {
      title: 'Contact',
      description: 'Contact information will be added here soon.'
    },
    imprint: {
      title: 'Imprint',
      description: 'This is the Imprint page. Legal information and impressum will be added here soon.'
    },
    systemParameters: {
      title: 'System Parameters',
      comingSoon: 'Coming soon...'
    },
    llmTraining: {
      title: 'LLM Training',
      comingSoon: 'Coming soon...'
    },
    multipleSources: {
      title: 'Multiple Sources',
      comingSoon: 'Coming soon...'
    },
    journalisticEvaluation: {
      title: 'Journalistic Evaluation',
      comingSoon: 'Coming soon...'
    },
    promptConstruction: {
      title: 'Prompt Construction',
      bias: {
        title: 'Bias',
        comingSoon: 'Coming soon...'
      },
      context: {
        title: 'Context',
        comingSoon: 'Coming soon...'
      },
      conversationStyle: {
        title: 'Conversation Style',
        comingSoon: 'Coming soon...'
      }
    }
  },
  es: {
    nav: {
      home: 'Inicio',
      modules: 'Módulos',
      about: 'Acerca de',
      contact: 'Contacto',
      imprint: 'Aviso Legal',
      guidedSimulator: 'Simulador Guiado',
      promptPlayground: 'Campo de Práctica de Prompts'
    },
    landing: {
      hero: {
        title: 'PromptED: Uso Responsable de IA en Periodismo',
        subtitle: 'Una exploración y práctica para periodistas para observar cómo funcionan los modelos de lenguaje grandes, sus limitaciones y cómo usarlos para una producción de contenido más confiable.',
        watchTrailer: 'Ver Tráiler'
      },
      features: {
        simulator: {
          title: 'Simulador Guiado',
          description: 'Guía interactiva: explora cómo funcionan los LLM y cómo interactuar responsablemente con ellos'
        },
        playground: {
          title: 'Campo de Práctica de Prompts',
          description: 'Aplica tus conocimientos: experimenta con tus propios prompts'
        },
        debunker: {
          title: 'Verificador de Afirmaciones de IA',
          description: 'Pon tus habilidades a trabajar: revisa afirmaciones y obtén perspectivas contrarias'
        }
      },
      footer: {
        llmUsage: 'Los LLM se han utilizado de las siguientes maneras:',
        guidedExploration: 'Exploración Guiada:',
        guidedExplorationDesc: 'Para crear ejemplos de prompt-salida.',
        promptPlayground: 'Campo de Práctica de Prompts:',
        promptPlaygroundDesc: 'Para optimizar prompts, generar salidas e identificar inexactitudes factuales y sesgos.',
        modelsUsed: 'Modelos utilizados:',
        models: 'Llama 3.1 8B, Mistral, Claude, ChatGPT',
        euFunding: "Financiado por el Programa Horizonte Europa de la Unión Europea (Subvención 101135437)"
      }
    },
    modules: {
      title: 'Módulos',
      comingSoon: 'Próximamente...',
      introduction: 'Introducción',
      nextWordPrediction: 'Predicción de Siguiente Palabra',
      promptConstruction: 'Construcción de Prompts'
    },
    intro: {
      aboutSimulator: {
        label: 'Acerca de este Simulador',
        title: '¿Qué es un "Simulador Guiado"?',
        description: 'Un recorrido estructurado de estudios de caso generados por salidas de LLM de la vida real que demuestran aprendizajes clave. Interactúa en puntos establecidos, a veces más, a veces menos, siempre con una guía clara.',
        llmsUsed: 'LLMs utilizados en la generación de texto incluyen: Mistral, Claude, Chat GPT y Llama 3.1 8B',
        continue: 'Continuar'
      },
      base: {
        label: 'Introducción',
        title: 'Reportaje sobre la Ley de IA de la UE',
        description: 'En este simulador, asumirás el papel de un periodista preparando un artículo sobre la Ley de IA de la UE. En lugar de comenzar desde cero, trabajarás con prompts predefinidos y verás las salidas reales generadas por un modelo de lenguaje grande.',
        startSimulator: 'Iniciar Simulador'
      }
    },
    nextWord: {
      intro: {
        label: 'Aprendizaje 1: Predicción de siguiente palabra',
        title: '¿Cómo forman los LLM respuestas a las indicaciones del usuario?',
        description: 'Los LLM generan texto prediciendo qué palabra debe venir a continuación. Para cada predicción, se analizan las palabras anteriores para calcular probabilidades para todas las palabras siguientes posibles. Se selecciona la palabra más probable, se añade al texto y luego se usa en este contexto actualizado para predecir la siguiente palabra, continuando hasta completarse.',
        continue: 'Continuar'
      }
    },
    promptConstructionModule: {
      intro: {
        label: 'Aprendizaje 2: Construcción de prompts',
        title: '¿Cómo afecta mi entrada a la calidad de la salida del LLM?',
        description: 'Tu prompt da forma directamente a la respuesta de un LLM. Los modelos de lenguaje grandes utilizan la redacción, especificidad y contexto en tu redacción para ayudar a decidir cómo responder, lo que significa que la calidad de la salida puede depender en gran medida de cómo lo formules. Explora cómo cambian las respuestas reales generadas por LLM con diferentes construcciones de prompts',
        continue: 'Continuar'
      }
    },
    about: {
      title: 'Acerca de',
      description: 'Esta es la página Acerca de. La información sobre el proyecto se agregará aquí pronto.'
    },
    contact: {
      title: 'Contacto',
      description: 'La información de contacto se agregará aquí pronto.'
    },
    imprint: {
      title: 'Aviso Legal',
      description: 'Esta es la página de Aviso Legal. La información legal se agregará aquí pronto.'
    },
    systemParameters: {
      title: 'Parámetros del Sistema',
      comingSoon: 'Próximamente...'
    },
    llmTraining: {
      title: 'Entrenamiento LLM',
      comingSoon: 'Próximamente...'
    },
    multipleSources: {
      title: 'Múltiples Fuentes',
      comingSoon: 'Próximamente...'
    },
    journalisticEvaluation: {
      title: 'Evaluación Periodística',
      comingSoon: 'Próximamente...'
    },
    promptConstruction: {
      title: 'Construcción de Prompts',
      bias: {
        title: 'Sesgo',
        comingSoon: 'Próximamente...'
      },
      context: {
        title: 'Contexto',
        comingSoon: 'Próximamente...'
      },
      conversationStyle: {
        title: 'Estilo de Conversación',
        comingSoon: 'Próximamente...'
      }
    }
  }
};
